In [2]:
import numpy as np
L = 4;
Nup = 3;
Ndn = 2;
K = np.zeros((L,L));
for i in range(L-1):
    K[i, i+1] = -1
    K[i+1, i] = -1
print( K)

[[ 0. -1.  0.  0.]
 [-1.  0. -1.  0.]
 [ 0. -1.  0. -1.]
 [ 0.  0. -1.  0.]]


In [30]:
w,v = np.linalg.eig(K)
idx = w.argsort()[::-1]   
w = w[idx]
v = v[:,idx]
print("Ground State Wave function for Spin up:")
print(v[:, 0:Nup])
print("Ground State Wave function for Spin down:")
print(v[:, 0:Ndn])

Ground State Wave function for Spin up:
[[-0.37174803  0.60150096 -0.60150096]
 [ 0.60150096 -0.37174803 -0.37174803]
 [-0.60150096 -0.37174803  0.37174803]
 [ 0.37174803  0.60150096  0.60150096]]
Ground State Wave function for Spin down:
[[-0.37174803  0.60150096]
 [ 0.60150096 -0.37174803]
 [-0.60150096 -0.37174803]
 [ 0.37174803  0.60150096]]


In [33]:
import scipy
from sklearn.preprocessing import normalize
tau = 0.01
M = 1000
exp_minus_tau_K = scipy.linalg.expm(-tau*K) 
phiT_up = np.random.rand(L,Nup)
phiT_dn = np.random.rand(L,Ndn)
for i in range(M):
    phiT_up = exp_minus_tau_K.dot( phiT_up )
    phiT_dn = exp_minus_tau_K.dot( phiT_dn )
phi0_up = normalize(phiT_up, axis=0, norm='l2')
phi0_dn = normalize(phiT_dn, axis=0, norm='l2')
print("Ground State Wave function for Spin up:")
print(phi0_up)
print("Ground State Wave function for Spin down:")
print(phi0_dn)

Ground State Wave function for Spin up:
[[0.37175303 0.37174401 0.37174183]
 [0.60150404 0.60149847 0.60149712]
 [0.60149787 0.60150344 0.60150479]
 [0.37174304 0.37175206 0.37175424]]
Ground State Wave function for Spin down:
[[0.37173983 0.37173718]
 [0.60149588 0.60149425]
 [0.60150603 0.60150766]
 [0.37175624 0.37175889]]


In [34]:
phi0_up, r = np.linalg.qr(phiT_up)
phi0_dn, r = np.linalg.qr(phiT_dn)
print("Ground State Wave function for Spin up:")
print(phi0_up)
print("Ground State Wave function for Spin down:")
print(phi0_dn)

Ground State Wave function for Spin up:
[[-0.37175303 -0.60149875  0.60144567]
 [-0.60150404 -0.37174249 -0.37166056]
 [-0.60149787  0.37175358 -0.3718355 ]
 [-0.37174304  0.60150316  0.60155623]]
Ground State Wave function for Spin down:
[[-0.37173983 -0.60149827]
 [-0.60149588 -0.37176103]
 [-0.60150603  0.37173504]
 [-0.37175624  0.60150364]]
